production:
  clients:
    uri: mongodb://heroku_ttzftlmb:ia1l7c4ktf4k4moh42i1vs76mi@ds157078.mlab.com:57078/heroku_ttzftlmb
    options:
      connect_timeout: 15

development:
  clients:
    default:
      database: custom_fields_development
      hosts:
        - localhost:27017
      options:

  options:
test:
  clients:
    default:
      database: custom_fields_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
